# Generated by Django 5.1.3 on 2025-04-17 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_type', models.CharField(choices=[('collision_probability', 'Collision Probability Prediction'), ('miss_distance', 'Miss Distance Prediction'), ('conjunction_risk', 'Conjunction Risk Classification')], max_length=30)),
                ('algorithm', models.CharField(choices=[('random_forest', 'Random Forest'), ('gradient_boosting', 'Gradient Boosting'), ('neural_network', 'Neural Network'), ('svm', 'Support Vector Machine'), ('ensemble', 'Ensemble Model')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('training', 'Training in Progress'), ('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Training Failed')], default='training', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('training_parameters', models.JSONField(blank=True, null=True)),
                ('feature_columns', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_probability', models.FloatField(blank=True, null=True)),
                ('predicted_miss_distance', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, max_length=20, null=True)),
                ('prediction_time', models.DateTimeField(auto_now_add=True)),
                ('explanation_data', models.JSONField(blank=True, null=True)),
                ('cdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='api.cdm')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.mlmodel')),
            ],
            options={
                'ordering': ['-prediction_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('training_data_count', models.IntegerField(default=0)),
                ('validation_data_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to=settings.AUTH_USER_MODEL)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='api.mlmodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
